[package]
name = "starkom-poseidon2"
version = "1.1.0"
description = "Starkom's implementation of the Poseidon2 algebraic hash."
license = "Apache-2.0"
repository = "https://github.com/libernet-xyz/poseidon2.git"
readme = "README.md"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
blstrs = { version = "0.7.1", optional = true }
ff = { version = "0.13.1", features = ["derive"] }
starkom-bluesky = { path = "bluesky", version = "2.1.0", optional = true }

[dev-dependencies]
primitive-types = "0.14.0"

[features]
default = ["bluesky"]
bls12_381 = ["blstrs"]
bluesky = ["starkom-bluesky"]
